apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "* */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: file_transfer_app
            image: chante/file_transfer_app:v1.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: efs
              mountPath: "/opt/src/"

          restartPolicy: OnFailure
          volumes:
          - name: efs
            persistentVolumeClaim:
              claimName: nfs-pvc-pv1