apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.43.5
    path: "/temp"